//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorWCF_Kliens.BorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultContract", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
    [System.SerializableAttribute()]
    public partial class FaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bor", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
    [System.SerializableAttribute()]
    public partial class Bor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlkoholField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CukorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FajtaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Alkohol {
            get {
                return this.AlkoholField;
            }
            set {
                if ((this.AlkoholField.Equals(value) != true)) {
                    this.AlkoholField = value;
                    this.RaisePropertyChanged("Alkohol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cukor {
            get {
                return this.CukorField;
            }
            set {
                if ((object.ReferenceEquals(this.CukorField, value) != true)) {
                    this.CukorField = value;
                    this.RaisePropertyChanged("Cukor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fajta {
            get {
                return this.FajtaField;
            }
            set {
                if ((object.ReferenceEquals(this.FajtaField, value) != true)) {
                    this.FajtaField = value;
                    this.RaisePropertyChanged("Fajta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_id {
            get {
                return this.User_idField;
            }
            set {
                if ((this.User_idField.Equals(value) != true)) {
                    this.User_idField = value;
                    this.RaisePropertyChanged("User_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BorServiceReference.IBorService")]
    public interface IBorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/getUsername", ReplyAction="http://tempuri.org/IBorService/getUsernameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BorWCF_Kliens.BorServiceReference.FaultContract), Action="http://tempuri.org/IBorService/getUsernameFaultContractFault", Name="FaultContract", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
        string getUsername(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/getUsername", ReplyAction="http://tempuri.org/IBorService/getUsernameResponse")]
        System.Threading.Tasks.Task<string> getUsernameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Login", ReplyAction="http://tempuri.org/IBorService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BorWCF_Kliens.BorServiceReference.FaultContract), Action="http://tempuri.org/IBorService/LoginFaultContractFault", Name="FaultContract", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
        string Login(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Login", ReplyAction="http://tempuri.org/IBorService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Logout", ReplyAction="http://tempuri.org/IBorService/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BorWCF_Kliens.BorServiceReference.FaultContract), Action="http://tempuri.org/IBorService/LogoutFaultContractFault", Name="FaultContract", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
        string Logout(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Logout", ReplyAction="http://tempuri.org/IBorService/LogoutResponse")]
        System.Threading.Tasks.Task<string> LogoutAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Add", ReplyAction="http://tempuri.org/IBorService/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BorWCF_Kliens.BorServiceReference.FaultContract), Action="http://tempuri.org/IBorService/AddFaultContractFault", Name="FaultContract", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
        string Add(string fajta, int alkohol, string cukor, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Add", ReplyAction="http://tempuri.org/IBorService/AddResponse")]
        System.Threading.Tasks.Task<string> AddAsync(string fajta, int alkohol, string cukor, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/List", ReplyAction="http://tempuri.org/IBorService/ListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BorWCF_Kliens.BorServiceReference.FaultContract), Action="http://tempuri.org/IBorService/ListFaultContractFault", Name="FaultContract", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
        BorWCF_Kliens.BorServiceReference.Bor[] List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/List", ReplyAction="http://tempuri.org/IBorService/ListResponse")]
        System.Threading.Tasks.Task<BorWCF_Kliens.BorServiceReference.Bor[]> ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Update", ReplyAction="http://tempuri.org/IBorService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BorWCF_Kliens.BorServiceReference.FaultContract), Action="http://tempuri.org/IBorService/UpdateFaultContractFault", Name="FaultContract", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
        string Update(int id, string fajta, int alkohol, string cukor, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Update", ReplyAction="http://tempuri.org/IBorService/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(int id, string fajta, int alkohol, string cukor, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Delete", ReplyAction="http://tempuri.org/IBorService/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BorWCF_Kliens.BorServiceReference.FaultContract), Action="http://tempuri.org/IBorService/DeleteFaultContractFault", Name="FaultContract", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
        string Delete(int borId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Delete", ReplyAction="http://tempuri.org/IBorService/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(int borId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Connection", ReplyAction="http://tempuri.org/IBorService/ConnectionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BorWCF_Kliens.BorServiceReference.FaultContract), Action="http://tempuri.org/IBorService/ConnectionFaultContractFault", Name="FaultContract", Namespace="http://schemas.datacontract.org/2004/07/BorWCF_Szerver")]
        BorWCF_Kliens.BorServiceReference.FaultContract Connection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBorService/Connection", ReplyAction="http://tempuri.org/IBorService/ConnectionResponse")]
        System.Threading.Tasks.Task<BorWCF_Kliens.BorServiceReference.FaultContract> ConnectionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBorServiceChannel : BorWCF_Kliens.BorServiceReference.IBorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BorServiceClient : System.ServiceModel.ClientBase<BorWCF_Kliens.BorServiceReference.IBorService>, BorWCF_Kliens.BorServiceReference.IBorService {
        
        public BorServiceClient() {
        }
        
        public BorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getUsername(int id) {
            return base.Channel.getUsername(id);
        }
        
        public System.Threading.Tasks.Task<string> getUsernameAsync(int id) {
            return base.Channel.getUsernameAsync(id);
        }
        
        public string Login(string name, string password) {
            return base.Channel.Login(name, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string name, string password) {
            return base.Channel.LoginAsync(name, password);
        }
        
        public string Logout(string id) {
            return base.Channel.Logout(id);
        }
        
        public System.Threading.Tasks.Task<string> LogoutAsync(string id) {
            return base.Channel.LogoutAsync(id);
        }
        
        public string Add(string fajta, int alkohol, string cukor, string user) {
            return base.Channel.Add(fajta, alkohol, cukor, user);
        }
        
        public System.Threading.Tasks.Task<string> AddAsync(string fajta, int alkohol, string cukor, string user) {
            return base.Channel.AddAsync(fajta, alkohol, cukor, user);
        }
        
        public BorWCF_Kliens.BorServiceReference.Bor[] List() {
            return base.Channel.List();
        }
        
        public System.Threading.Tasks.Task<BorWCF_Kliens.BorServiceReference.Bor[]> ListAsync() {
            return base.Channel.ListAsync();
        }
        
        public string Update(int id, string fajta, int alkohol, string cukor, string user) {
            return base.Channel.Update(id, fajta, alkohol, cukor, user);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(int id, string fajta, int alkohol, string cukor, string user) {
            return base.Channel.UpdateAsync(id, fajta, alkohol, cukor, user);
        }
        
        public string Delete(int borId, string user) {
            return base.Channel.Delete(borId, user);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(int borId, string user) {
            return base.Channel.DeleteAsync(borId, user);
        }
        
        public BorWCF_Kliens.BorServiceReference.FaultContract Connection() {
            return base.Channel.Connection();
        }
        
        public System.Threading.Tasks.Task<BorWCF_Kliens.BorServiceReference.FaultContract> ConnectionAsync() {
            return base.Channel.ConnectionAsync();
        }
    }
}
